version: '3'

services:
  async_engine_server:
    restart: unless-stopped
    container_name: async_engine_server
    ports:
      - "80:8081"
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    networks:
      fotis_net:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
        - '/data/db:/data/db'
        - '/data/configdb:/data/configdb'
    networks:
      fotis_net:
networks:
  fotis_net:
     driver: bridge
